{{- include "init" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: jukebox-conf
  namespace: {{ .conf.namespace | quote }}
  labels:
    app: jukebox
    {{- include "commonLabels" . | nindent 4 }}
data:
  conf.yaml: |
    enable_spotify: false
    device_name: ""
    post_init_command: ""
    volume_up_command: ""
    volume_down_command: ""
    trigger_only_mode: false
    audio_base_directory: "/mnt/jukebox-audio"
    tag_mapper_configuration_file: "tag-mapper.yaml"
    pause_pin: 14
    enable_rfid_controller: true
    debug: false
    audio_output_device: "default:CARD=vc4hdmi0"
