{{- include "init" . -}}
{{- if .conf.rclone.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: rclone-config
  namespace: {{ .conf.namespace | quote }}
  labels:
    app: rclone
    {{- include "commonLabels" . | nindent 4 }}
type: Opaque
stringData:
  rclone.conf: |
    {{- required "Missing: rclone.secretConfiguration" .conf.rclone.secretConfiguration | nindent 4 }}
{{- end }}
